version: '3.1'

services:

  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: investportfolio_dev

  webapp:
    build: .
    command: java -Dspring.profiles.active=docker -jar *.jar
    depends_on:
      - db
    ports:
      - "8080:8080"

