spring:
  mvc:
    format:
      date: iso

  datasource:
    url: jdbc:postgresql://db:5432/investportfolio_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false

logging:
  level:
    root: info
  file:
    path: logs
