spring:
  mvc:
    format:
      date: iso

  datasource:
    url: jdbc:postgresql://dpg-cfl4mfpa6gductitalv0-a:5432/investportfolio
    username: investportfolio_user
    password: 9VNStEKWY1TbxUdSqorby7MwnT6jUQ8Q
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false

debug: true

#logging:
#  level:
#    root: info
#  file:
#    path: logs